In [1]:
import numpy as np

In [2]:
N = 5
M = 4
K = 2

In [3]:
R = np.array([
 [5,3,0,1],
 [4,0,0,1],
 [1,1,0,5],
 [1,0,0,4],
 [0,1,5,4]
])

In [4]:
R[0,1]

3

In [5]:
def nnmf(R, K=2, loop=5000, a=0.0001, b=0.02):
    P = np.random.rand(R.shape[0], K)
    Q = np.random.rand(K, R.shape[1])
    
    for l in xrange(loop):
        for i in xrange(R.shape[0]):
            for j in xrange(R.shape[1]):
                # error
                if 0 < R[i,j]:
                    
                    #error between real R and estimates
                    eij = R[i,j] - np.dot(P[i,:], Q[:,j])
                
                    # update on gradient descents
                    P_n = P
                    Q_n = Q
                    for k in xrange(K):
                        #add gradients
                        P_n[i,k] = P[i,k] + a*(2*eij*Q[k,j] - b*P[i,k])
                        Q_n[k,j] = Q[k,j] + a*(2*eij*P[i,k] - b*Q[k,j])
                    
                        P[i,k] = P_n[i,k]
                        Q[k,j] = Q_n[k,j]
    
    
        # total error check
        e_t = 0
        for i in xrange(R.shape[0]):
            for j in xrange(R.shape[1]):
                if 0 < R[i,j]:
                    e_t = e_t + pow(R[i,j] - np.dot(P[i,:], Q[:,j]), 2)
                    
                    for k in xrange(K):
                        e_t = e_t + b/2 * ( pow(P[i,k],2) + pow(Q[k,j],2) )
        
        #escape
        if l % 1000 == 0:
            print 'loop %s, total error : %s' % (l, e_t)
        
        if e_t < 0.001:
            break
            
    print 'loop finished. \n R : \n', R, '\n P : \n', P, '\n Q : \n',Q



In [6]:
nnmf(R, 2, 10000)

loop 0, total error : 105.880391449
loop 1000, total error : 31.3445671915
loop 2000, total error : 18.9490838098
loop 3000, total error : 7.03287500247
loop 4000, total error : 4.11385000047
loop 5000, total error : 3.50200790086
loop 6000, total error : 3.10815863589
loop 7000, total error : 2.78700803466
loop 8000, total error : 2.51845747364
loop 9000, total error : 2.29396321354
loop finished. 
 R : 
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]] 
 P : 
[[ 0.46203642  2.3490777 ]
 [ 0.44652817  1.76746808]
 [ 1.93818106  0.0161685 ]
 [ 1.55341396  0.02038929]
 [ 1.58557814  1.22113931]] 
 Q : 
[[ 0.57342311  0.27042898  1.23551867  2.56959912]
 [ 2.05954822  1.04650727  2.33058465 -0.0762185 ]]
